### ISSUE TITLE
Additional questions / help regarding how this works

### ISSUE THREAD

**Issue by chill-cod3r** [patrickpissurno/fastify-esso#2]
Hi, this looks interesting although I'm relatively unfamiliar with how this type of authentication works.  I think it leaves a lot of implementation to the reader which is fine.  I'm sure that implementation is obvious to a lot of people, but for someone like myself that doesn't deal with authentication and authorization very often, (and most of what you hear about is oauth these days which usually leads to someone saying "just use okta, firebase, or auth0" which I don't really want to do) would you happen to be able to provide some pointers or examples (or possibly answer the questions below) with some of the implementation that's semi-indirectly related to this package?

- would this still benefit from a password comparison using something like bcrypt?
- where does expiration come into play in this model?
- how would you support secret rotation in this model without invalidating existing "logins"?
- is there an example application reference somewhere that uses this model of authentication and authorization that creates users, authenticates and authorizes them, and provides access to a protected resource? (ideally with thoughts on how to lock out bad actors once detected)

**Comment by patrickpissurno** [comment]
Hi! I'll try to address all of your questions. If something is still not clear, feel free to keep asking for help.

<hr>

> would this still benefit from a password comparison using something like bcrypt?

Definitely! This plugin doesn't implement credentials validation. This is left out to be implemented by the application. In the readme you can find an example that uses plain password comparison (not recommended, just to keep stuff simple)

In production you may want to store random salted SHA256 hashes of your user's passwords in the database of your choice. Just make sure your salts are different for each user and you should be fine. You could also use bcrypt or scrypt for that.

Then all you have to do is:
- retrieve from your database the stored hash and salt for the requesting user
- compute the hash for the password received with the request
- use `crypto.timingSafeEqual` to compare both hashes. Do NOT use `===` or `==` to do that kind of comparison. Always use `crypto.timingSafeEqual` to prevent timing attacks
- if it returns false, then password is wrong
- if it returns true, then proceed to generate the auth token with `fastify.generateAuthToken`

<hr>

> where does expiration come into play in this model?

Nice one. It can be implemented with ease by a combination of two things the plugin provides:
- You can pass custom data to `fastify.generateAuthToken`. Example: `fastify.generateAuthToken({ expires: moment().add(7, 'days').unix() })` (PS: you could also do it in pure JS, I just used moment.js for convenience)
- Specify an `extra_validation` function when registering the plugin, that checks if the expiration has already expired. Example:

```js
const opts = {
    secret: '11111111111111111111', // cannot be ommited
    
    /** request and reply are Fastify's request and reply **/
    extra_validation: async function validation (request, reply){ // can be ommited
        /**
         * Custom validation function that is called after basic validation is executed
         * This function should throw in case validation fails
         * req.auth is already available here
         */
        if(moment.unix(req.auth.expires).isBefore(moment()))
            return { expired: true };
    }
};

fastify.register(require('fastify-esso')(opts));
```

This combination is very powerful. You could implement a bunch of custom checks, permissions and other complex things.
Also, you can modify the `req.auth` object inside that function and then you'll get access to the modified version in every authenticated fastify route.

<hr>

> how would you support secret rotation in this model without invalidating existing "logins"

This is something that you could implement by creating a second routefor authentication, for example, POST /refresh_token. That route would require the user to be authenticated, and thus require a valid token. The plugin will handle the authentication part for you, and all you'll have to do is generate a new token and return it. You could combine that with the example above and refresh the expiration time. The application consuming the API would then start using the new token instead of the older one.

<hr>

> is there an example application reference somewhere that uses this model of authentication and authorization that creates users, authenticates and authorizes them, and provides access to a protected resource? (ideally with thoughts on how to lock out bad actors once detected)

Seems like a nice addition to the project. This plugin is currently in production use for several (closed source) projects, but I don't know of any that is open source.

I'll look into writing a demo app that uses all the above. 

I'll leave this issue open, so feel free to keep asking for help here. It's nice because others might find it helpful too.

**Comment by chill-cod3r** [comment]
Awesome, thank you for the excellent responses.  I have some more when you have time 😊

- By secret rotation (forgive me if you were explaining this and I’m just not seeing it) I meant that I would expect the secret used to generate the tokens is some kind of environment variable. I’m used to scenarios where that secret should be rotated every 90 days or so. How would you support rotating the secret in this fashion while not forcibly logging out people with tokens that were generated using the secret that has been “rotated away”?

- is this type of auth recommended for multiple service to service and SPA front end to different backend services style authentication and authorization schemes? If so what tips would you have in that scenario? 

- what would the recommended strategy be for instantly locking out bad actors (token invalidation)?

- I read through the reference material in the readme however I feel like I’m missing something. All it seems you hear on the internet is about jwt and oauth. Is there any material you’d recommend that shares a deeper compare and contrast around why you might use this mechanism as opposed to the jwt schemes you see out there?


To further clarify The refresh flow, This is where my head goes to add to the base example however it’s probably wrong. Perhaps you could help me understand more clearly - let’s bring in a refresh token example. 
When user auths against an AS, you generate a token with a 5 min exp time, and then you also save a refresh token in a dB and send it back as well. When main token expires, send refresh so it can be verified against the dB and then a new token comes back. This helps in the case of lockout awareness but also adds surface area in other ways. What would be a proper or better way to achieve the same result while still affording a UX that doesn’t force people to authenticate over and over again?

**Comment by patrickpissurno** [comment]
> By secret rotation (forgive me if you were explaining this and I’m just not seeing it) I meant that I would expect the secret used to generate the tokens is some kind of environment variable. I’m used to scenarios where that secret should be rotated every 90 days or so. How would you support rotating the secret in this fashion while not forcibly logging out people with tokens that were generated using the secret that has been “rotated away”?

Sorry, I thought you were talking about how to refresh tokens. Well, at the moment I don't think it is possible (secret rotation), but I'll implement support for that tomorrow.

I'll support that by having two secrets: `old_secret` and `secret`. Let's call the secret rotation period `N` (in days).

- `secret` is your current secret (valid for `N / 2` days)
- `old_secret` is the secret that was in use before your current one (valid for `N / 2` days)

The plugin will first try to validate the token using your current `secret`. If it fails, it will try to validate the token using `old_secret`.

Combine that with the aforementioned token refresh strategy, and tokens generated with the `old_secret` will be automatically replaced by new tokens generated with the current `secret`.

If someone authenticates and doesn't refresh their token for `N` days, then and only then they get logged out.

Also, both secrets can be the same, or `old_secret` can be left null in order to be backwards compatible (a.k.a. no secret rotation).

If you have any ideas on how the plugin should support this, let's get some discussion going.

<hr>

> is this type of auth recommended for multiple service to service and SPA front end to different backend services style authentication and authorization schemes? If so what tips would you have in that scenario?

As with anything in C.S., it usually depends. But it will mostly work nicely in that case.

**Approach 1**

The way I'd implement is creating a microservice exclusive for refreshing tokens and signing the user in (credentials validation and token generation). I'll call that `microservice X`. No other back end services would implement that.

All the other services would just share the same secret in order to validate the token.

The SPA would first talk to `microservice X` to sign the user in or to refresh their token. Then, with that token, it would call the other services directly. Notice that with this approach, there's no need for communication between `microservice X` and all the others to exist. They can be in different VPCs or even phisically isolated, and authentication would still succeed as they both share the same secret.

Just keep in mind that you might need to setup CORS for the front end to be able to call APIs on distinct domain names.

**Approach 2**

Another approach would be to implement the plugin only in that `microservice X`, expose private endpoints for server-to-server token validation and then, upon receiving authenticated requests, all the other microservices would make a network call to `microservice X` in order to validate it.

This approach has some pros and cons vs. the first one (I'll just list some):

Pros:
- less maintenance overhead (rotate secret in one microservice vs. rotate in many)
- works better if some of your microservices are not written in JS (you would have to port the plugin and things would get complicated really fast)

Cons:
- reduced performance (i.e. no network calls vs. network calls)
- if the `microservice X` goes down, everything goes down with it (can be mitigated by deploying redundant replicas, which is not that complicated)

**Conclusion**

It's up to you which one is best. Sometimes you might even use a combination of both (if you decide to use the first approach but still need to support a few services written in other programming languages).

<hr>

> what would the recommended strategy be for instantly locking out bad actors (token invalidation)?

Well, `instantly` is kinda a strong word. There is currently no direct support for that. It is not that it can't be implemented. It's just it's not an easy task to support it without forcing developers to build centralized token validation structures (currently this plugin can also operate in a distributed fashion, an example being the first approach I just outlined above).

**First scenario**

If you really need it to be instantly, there is only one way: you'll have to create a black list and check the token or the user against it (can be implemented with help of the `extra_validation` function). That would have to be implemented in each and every authenticated microservice (in case you chose to use the Approach 1 of my reply to the last question).

**Second scenario**

If you can tolerate some delay (say 5 minutes, 10 minutes, an hour) you might get away combining low expiration times with automatic token refresh. Then you'll only have to implement the check for bad actors in: the token refresh route and regular user sign in route (a.k.a. wherever you generate tokens).

**Third scenario**

Similar to the First scenario, but in case you chose the Approach 2 of my reply to the last question. You would just have to implement the check in one microservice: the one that does all the authentication related stuff and exposes private endpoints for the other microservices.

**Fourth scenario**

If you can tolerate some delay, but don't want to refresh the token that often, you have the option to trade that for some propagation time. 

Build a distributed black list with eventual consistency. Let me drop the fancy words and put it in a simpler way: every service would pull that black list every so often (say 10 seconds). When validating requests, they would validate against their local copy of the black list, so performance-wise it's top-notch. The trade off being storage space and network traffic (could be mitigated by checking if the list changed before pulling, which can easily be accomplished by hashing the list and comparing the hashes. Could also be optimized further).

**Conclusion**
There might be other ways to do that. Distributed systems always have trade offs that must be taken into account when building then. Sadly there is no silver-bullet. Hope my considerations help you with that.

<hr>

> I read through the reference material in the readme however I feel like I’m missing something. All it seems you hear on the internet is about jwt and oauth. Is there any material you’d recommend that shares a deeper compare and contrast around why you might use this mechanism as opposed to the jwt schemes you see out there?

Well, you'll probably not find much related to this project on the web (if you do, please tell me, I'll be flattered) because while the ideas behind it are nothing new, I developed it further to fit my needs: something simple, easy to use and flexible. Standardized technologies (like JWT) sometimes tend to overcomplicate things and surely their learning curve is usually steep, because they usually try accomplish many things in a way that can be used in most technologies, for as many purposes as possible.

The other authentication plugins available for fastify (that I'm aware of) are so complicated or not flexible enough (imho). And that made me not use them and instead write custom authentication code again and again. That got me bored, specially when fixing bugs or when project requirements changed and suddenly I had a lot of non-uniform codebases to update (which means a lot of work). 

That's why this plugin exists. It's quite similar to JWT (by principle), despite not following it's spec. I know that it might be complicated, but I think that the only way of really getting some deeper understanding of the differences between this and JWT is to check the source code of `fastify-esso` after grasping a deep understanding of how JWT works, how its structure and everything.

Keep in mind that you could do everything I do in this plugin using JWT. But you would lose (or have to implement them yourself) many things this plugin already provides out-of-the-box.

> When user auths against an AS, you generate a token with a 5 min exp time, and then you also save a refresh token in a dB and send it back as well. When main token expires, send refresh so it can be verified against the dB and then a new token comes back. This helps in the case of lockout awareness but also adds surface area in other ways. What would be a proper or better way to achieve the same result while still affording a UX that doesn’t force people to authenticate over and over again?

Using a DB to store the tokens is exactly what this plugin tries to avoid altogether. In some of my aforementioned black list examples, one could say that they're using DBs to store tokens and thus breaking one of the core principles of this plugin. But upon a closer look, it's not the same thing. 

I hope those examples above fit your use-case. If not, please tell me and I'll try to write a code sample that features all of it.

By tomorrow I'll release an update to the plugin featuring proper support for secret rotation.

I appreciate your interest on using this.

**Comment by nalimhahs** [comment]
Hey, I was looking into the project and it looks pretty interesting. But I had a doubt and it would be great if you could clear it regarding logging out. (I'm asking here as more people could come here for something like an FAQ)

The question being how would you go about invalidating a token once it is generated on an action like logging out? Since we are not hitting the db to store or load any tokens, how could we mark them as invalid? 

One option i could think of the top of my head is just creating a new one but still the old one would still be valid till it expires. And any bad actor could use that to login. Did I miss anything?

**Comment by patrickpissurno** [comment]
Hi, thanks!

So, this is an issue shared with JWTs. Pretty much you only have a few options. The most common one is exactly what you proposed (and what we've been using in production):
- Remove the token client-side and you should be ok for the most part

You can mitigate the bad actor by using HTTPS + HSTS + storing the token in a server-side cookie. That way bad actors shouldn't (easily) be able to obtain the token via a MITM attack, nor via a XSS attack. The only way would be actually compromising the browser, in which case yeah, they'd get access to the token.

You can somewhat improve the above solution a little bit, although it can still be bypassed, by storing the user’s IP address in that token. So you can verify whether the request is coming from a different IP and deny it. That would make it so that bad actors would need to make requests from the same device (within the same network, in case the client is behind a NAT), which is possible but it does make things trickier for them.

As you can see, there's no silver bullet, sadly.

If the client isn't a web application, then you don't get that free server-side cookie protection, so try to use a somewhat safe place to store the token, although it probably won't be as safe as the server-side cookie solution. The good practice is use short-lived tokens and refresh them often.

That can easily be implemented by saving the login timestamp inside the token, and then checking to see if it expired during validation. Or storing the 'expires at' timestamp inside the token and checking if the current one is past that.

All in all, that won't allow you to instantly block someone. For that you have the following options:
- For non-sensitive routes, just leave it as is, it probably won't be an issue
- For sensitive ones, hit the database so you can really make sure the user is allowed to have access to it

That way you still benefit from not having to hit the database as often, but still secure the most sensitive routes.

Another option is to do the same as the above, but instead of using a database, use something like Redis to store a token (and/or user) blocklist. Redis is pretty fast, and you can set each blocklist entry to expire automatically so that it matches the remaining token duration. It does diminish the benefit of using this kind of stateless authentication mechanism, but if you only do that for sensitive routes, you still get to benefit at least a bit from it.

As I said at first, there's no perfect solution to this issue. It's a trade-off for not having to hit the database as often. This is also an issue when using JWTs, so a tip is to look up for JWT solutions to it. Like this StackOverflow's post:
[https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens](https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens)

Anyway, if you need to invalidate all tokens at once, it can be done by simply changing the secret. In that case all tokens go invalid instantly. It's definitely something cumbersome to do, but it's safe and instant. So, if for any reason you need to do that, that's a pretty good way to go.

Hope it helps!

**Comment by nalimhahs** [comment]
Aah that makes much more sense now. Thanks a lot for taking the time to explain this!
